name: "CI/CD Pipeline"

on:
  push:
    branches:
      - main

concurrency:
  group: pipeline-bull-board-docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-and-push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main' # Only run this and a few other steps when deploying (oe merge to main)
        id: buildx
        with:
          install: true
        uses: docker/setup-buildx-action@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-base-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-base-${{ hashFiles('**/package-lock.json') }}
            npm-base-
            npm-
      - name: Versioning
        env:
          TAG: ${{ github.sha }}
          VERSION: ${{ github.sha }}
        run: printf "VERSION=$VERSION\nTAG=$TAG" >> versions.env
      - name: NPM CI
        run: npm ci
      - name: NPM Prebuild
        run: npm run prebuild
      - name: NPM Build
        run: npm run build
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Reset Multiarch Container
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build Image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            probablynot/bull-board-docker:latest
            probablynot/bull-board-docker:${{ github.sha }}
          platforms: |
            linux/amd64
            linux/arm64
